#!/usr/bin/env python3
"""Compile the quick-study layer: per-section cram sheets + primers.

Input:  data/study/s<X>.json — authored by generation agents, fact-checked
        before shipping (provenance.fact_checked). Structure:
        {
          "section": "s8",
          "primers": [{"objective": "s8o1", "title": str,
                        "body_md": str, "citations": [url, ...]}],
          "facts":   [{"objective": "s8o1", "fact_md": str,
                        "source": {"type": "citation"|"proof", "ref": url|qid}}],
          "provenance": {"generated": date, "model": str,
                          "fact_checked": bool, "notes": str}
        }
Output: site/docs/cram/s<X>.mdx (one cram page per section with a study file).

Rules enforced here (build fails otherwise):
 - every primer/fact objective exists in the section's syllabus entry
 - every objective of the section is covered by >= 1 primer and >= 2 facts
 - every primer has >= 1 citation; every fact has a source
 - proof-type sources reference an existing question id
 - only fact_checked files ship (unchecked files fail the build — the
   fact-check pass is part of the generation contract, like verify_bank)
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from build_site_data import esc_mdx  # same escaping rules as section pages

ROOT = Path(__file__).resolve().parent.parent
STUDY_DIR = ROOT / "data" / "study"
QUESTIONS_DIR = ROOT / "data" / "questions"
OUT_DIR = ROOT / "site" / "docs" / "cram"

PAGE_TEMPLATE = """---
sidebar_position: {pos}
title: "Cram: {num} · {title}"
description: "Quick-study sheet for exam section {num}: background primers and verified key facts."
---

{generated_note}

# Cram sheet — Section {num}: {title}

One-screen review layer for this section: short background primers per
objective, then the key facts — each backed by an official source or by an
executed proof from the question bank.

{body}

---

*Every fact above is sourced: 📖 links go to official documentation, ⚙️ marks
facts observed by executing code against the pinned Qiskit stack (the linked
section page shows the proof evidence on its practice questions).*
"""

GENERATED_NOTE = (
    "{/* AUTO-GENERATED by pipeline/build_study.py from data/study/ — "
    "do not edit by hand. */}"
)


def fail(msg: str) -> None:
    print(f"build_study: ERROR: {msg}", file=sys.stderr)
    raise SystemExit(1)


def question_ids() -> set[str]:
    """Only EXECUTED questions may back a ⚙️ proof-sourced fact — a
    conceptual qid would ship a false 'proven by execution' badge."""
    ids = set()
    for p in QUESTIONS_DIR.glob("s*/*.json"):
        q = json.loads(p.read_text())
        if q.get("proof", {}).get("status") == "executed" and (
            ROOT / "data" / "proofs" / f"{p.stem}.json"
        ).exists():
            ids.add(p.stem)
    return ids


def render_fact(fact: dict, sid: str) -> str:
    src = fact["source"]
    if src["type"] == "citation":
        slug = src["ref"].rstrip("/").split("/")[-1]
        tail = f" — 📖 [{esc_mdx(slug)}]({src['ref']})"
    else:
        tail = f" — ⚙️ proven in [`{src['ref']}`](/docs/sections/{sid})"
    return f"- {esc_mdx(fact['fact_md'])}{tail}"


def build_section(study: dict, syllabus_section: dict, qids: set[str]) -> str:
    sid = study["section"]
    objectives = {o["id"]: o["text"] for o in syllabus_section["objectives"]}

    prov = study.get("provenance") or {}
    if not prov.get("fact_checked"):
        fail(f"{sid}: study file is not fact_checked — run the fact-check pass first")

    primers_by_obj: dict[str, list[dict]] = {}
    for p in study.get("primers", []):
        if p["objective"] not in objectives:
            fail(f"{sid}: primer references unknown objective {p['objective']}")
        if not p.get("citations"):
            fail(f"{sid}: primer '{p.get('title')}' has no citations")
        primers_by_obj.setdefault(p["objective"], []).append(p)

    facts_by_obj: dict[str, list[dict]] = {}
    for f in study.get("facts", []):
        if f["objective"] not in objectives:
            fail(f"{sid}: fact references unknown objective {f['objective']}")
        src = f.get("source") or {}
        if src.get("type") not in ("citation", "proof"):
            fail(f"{sid}: fact missing a valid source: {f['fact_md'][:60]}")
        if src["type"] == "proof" and src["ref"] not in qids:
            fail(f"{sid}: fact cites unknown question {src['ref']}")
        facts_by_obj.setdefault(f["objective"], []).append(f)

    for oid in objectives:
        if oid not in primers_by_obj:
            fail(f"{sid}: objective {oid} has no primer")
        if len(facts_by_obj.get(oid, [])) < 2:
            fail(f"{sid}: objective {oid} has fewer than 2 facts")

    blocks = []
    for oid, otext in objectives.items():
        blocks.append(f"## {esc_mdx(otext)}\n")
        for p in primers_by_obj[oid]:
            blocks.append(f"### {esc_mdx(p['title'])}\n")
            blocks.append(esc_mdx(p["body_md"]) + "\n")
            refs = " · ".join(
                f"[{esc_mdx(u.rstrip('/').split('/')[-1])}]({u})" for u in p["citations"]
            )
            blocks.append(f"*Sources: {refs}*\n")
        blocks.append("**Key facts:**\n")
        for f in facts_by_obj[oid]:
            blocks.append(render_fact(f, sid))
        blocks.append("")
    return "\n".join(blocks)


def main() -> int:
    syllabus = json.loads((ROOT / "data" / "syllabus.json").read_text())
    sections = {s["id"]: s for s in syllabus["sections"]}
    qids = question_ids()

    files = sorted(STUDY_DIR.glob("s*.json")) if STUDY_DIR.exists() else []
    if not files:
        print("build_study: no study files yet — nothing to do")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "_category_.json").write_text(
        json.dumps(
            {
                "label": "Cram sheets",
                "position": 4,
                "collapsed": True,
                "link": None,
            },
            indent=2,
        )
        + "\n"
    )

    built = 0
    for path in files:
        study = json.loads(path.read_text())
        sid = study["section"]
        if sid != path.stem:
            fail(f"{path.name}: section {sid} does not match filename")
        sec = sections.get(sid) or fail(f"{path.name}: unknown section {sid}")
        num = sid[1:]
        body = build_section(study, sec, qids)
        page = PAGE_TEMPLATE.format(
            pos=int(num),
            num=num,
            title=esc_mdx(sec["title"]),
            generated_note=GENERATED_NOTE,
            body=body,
        )
        (OUT_DIR / f"{sid}.mdx").write_text(page)
        built += 1
    print(f"build_study: {built} cram page(s) -> site/docs/cram/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
