#!/usr/bin/env python
"""Compile data/ into site artifacts.

Outputs (all generated — do not hand-edit):
  site/src/data/bank/s1..s8.json   per-section question bank for the UI
                                   (proof scripts stripped, proof evidence embedded)
  site/src/data/syllabus.json      section metadata for dashboard / mock exam
  site/docs/sections/<sX>.mdx      section study pages (objectives, resources, drill)

Only shippable questions are included: schema-valid AND (executed proofs:
artifact present + freshness not stale; conceptual: always). Run after
verify_bank.py.

Usage: .venv/bin/python pipeline/build_site_data.py
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from harness.schema import QuestionError, load_question  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
DATA = REPO / "data"
SITE = REPO / "site"
BANK_OUT = SITE / "src" / "data" / "bank"
DOCS_SECTIONS = SITE / "docs" / "sections"

GENERATED_NOTE = "{/* GENERATED by pipeline/build_site_data.py — do not edit by hand */}"


def esc_mdx(text: str) -> str:
    """Escape MDX-hostile characters outside inline-code spans."""
    parts = re.split(r"(`[^`]*`)", text)
    out = []
    for part in parts:
        if part.startswith("`") and part.endswith("`"):
            out.append(part)
        else:
            out.append(
                part.replace("{", "&#123;")
                .replace("}", "&#125;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
            )
    return "".join(out)


def load_bank() -> tuple[dict, list[str]]:
    """Return {section_id: [question,...]} of shippable questions + warnings."""
    bank: dict[str, list[dict]] = {}
    warnings: list[str] = []
    for path in sorted((DATA / "questions").glob("s*/*.json")):
        try:
            q = load_question(path)
        except QuestionError as e:
            warnings.append(f"SKIP {path.stem}: {e}")
            continue
        if q["proof"]["status"] == "executed":
            fresh = q.get("freshness", {})
            artifact_rel = q["proof"].get("artifact")
            artifact = DATA / artifact_rel if artifact_rel else None
            if fresh.get("stale", True) or not (artifact and artifact.exists()):
                warnings.append(f"SKIP {q['id']}: no fresh proof")
                continue
            proof_data = json.loads(artifact.read_text())
            verdict = proof_data.get("verdict") or {}
            proof_view = {
                "status": "executed",
                "evidence": verdict.get("evidence", {}),
                "versions": proof_data.get("versions", {}),
                "verifiedOn": fresh.get("verified_on"),
                "wallSeconds": proof_data.get("wall_seconds"),
            }
        else:
            proof_view = {"status": "conceptual"}
        bank.setdefault(q["section"], []).append(
            {
                "id": q["id"],
                "section": q["section"],
                "objectives": q["objectives"],
                "type": q["type"],
                "difficulty": q["difficulty"],
                "stem": q["stem"],
                "code": q["code"],
                "options": q["options"],
                "answer": q["answer"],
                "explanation": q["explanation"],
                "proof": proof_view,
                "provenance": {
                    "generated": q["provenance"]["generated"],
                    "model": q["provenance"]["model"],
                    "adversarialRounds": q["provenance"]["adversarial_rounds"],
                },
            }
        )
    return bank, warnings


def section_meta(sec: dict) -> dict:
    return {
        "id": sec["id"],
        "num": sec["num"],
        "title": sec["title"],
        "weightPct": sec["weight_pct"],
        "objectives": [{"id": o["id"], "text": o["text"]} for o in sec["objectives"]],
    }


def write_bank(syllabus: dict, bank: dict) -> dict:
    BANK_OUT.mkdir(parents=True, exist_ok=True)
    stats = {}
    for sec in syllabus["sections"]:
        sid = sec["id"]
        questions = bank.get(sid, [])
        payload = {"section": section_meta(sec), "questions": questions}
        (BANK_OUT / f"{sid}.json").write_text(
            json.dumps(payload, ensure_ascii=False) + "\n"
        )
        stats[sid] = len(questions)
    return stats


def write_syllabus_meta(syllabus: dict, stats: dict) -> None:
    payload = {
        "exam": {
            "code": syllabus["exam"]["code"],
            "questions": syllabus["exam"]["questions"],
            "minutes": syllabus["exam"]["minutes"],
            "passScore": syllabus["exam"]["pass_score"],
        },
        "sections": [
            {**section_meta(s), "bankCount": stats.get(s["id"], 0)}
            for s in syllabus["sections"]
        ],
    }
    (SITE / "src" / "data" / "syllabus.json").write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n"
    )


SECTION_TEMPLATE = """---
sidebar_position: {pos}
title: "{num} · {title}"
description: "Exam section {num} ({weight}% of the exam): objectives, official resources, and verified practice questions."
---

{generated_note}

import PracticeSet from '@site/src/components/Quiz/PracticeSet';
import DoqExtras from '@site/src/components/DoqExtras';

# Section {num} — {title}

**{weight}% of the exam** · ≈ {approx_q} of 68 questions{bank_line}

## What the exam expects

{objectives_block}

<details>
<summary>Scope notes — what to actually master</summary>

{scope_block}

</details>

## Learn — official resources

The exam is based on these official IBM materials. Study them first; the drills below tell you when you're done.

{resources_block}

<DoqExtras slugs={{{doq_slugs}}} />

## Drill — verified practice

Every code-bearing question below was executed against a pinned Qiskit 2.x stack at build time; explanations show the actual execution evidence.

<PracticeSet section="{sid}" />
"""


def write_section_pages(syllabus: dict, stats: dict) -> None:
    DOCS_SECTIONS.mkdir(parents=True, exist_ok=True)
    (DOCS_SECTIONS / "_category_.json").write_text(
        json.dumps(
            {
                "label": "Exam sections",
                "position": 3,
                "collapsed": False,
                "link": None,
            },
            indent=2,
        )
        + "\n"
    )
    total_weight = sum(s["weight_pct"] for s in syllabus["sections"])
    for sec in syllabus["sections"]:
        sid = sec["id"]
        approx_q = round(syllabus["exam"]["questions"] * sec["weight_pct"] / total_weight)
        objectives_block = "\n".join(
            f"- **{esc_mdx(o['text'])}** (`{o['id']}`)" for o in sec["objectives"]
        )
        scope_block = "\n".join(f"- {esc_mdx(n)}" for n in sec.get("scope_notes", []))
        res_lines = []
        for r in sec.get("resources", []):
            if r.get("url"):
                res_lines.append(
                    f"| [{esc_mdx(r['title'])}]({r['url']}) | {r['type']} |"
                )
        resources_block = (
            "| Resource | Type |\n|---|---|\n" + "\n".join(res_lines)
            if res_lines
            else "_Resource links are being verified._"
        )
        count = stats.get(sid, 0)
        bank_line = (
            f" · **{count} verified practice questions**" if count else ""
        )
        doq_slugs = json.dumps(
            [
                r["url"].rstrip("/").rsplit("/", 1)[-1]
                for r in sec.get("resources", [])
                if r.get("url") and r.get("type") == "guide"
            ]
        )
        page = SECTION_TEMPLATE.format(
            pos=sec["num"],
            num=sec["num"],
            title=esc_mdx(sec["title"]),
            weight=sec["weight_pct"],
            approx_q=approx_q,
            bank_line=bank_line,
            objectives_block=objectives_block,
            scope_block=scope_block or "_See objectives above._",
            resources_block=resources_block,
            sid=sid,
            doq_slugs=doq_slugs,
            generated_note=GENERATED_NOTE,
        )
        (DOCS_SECTIONS / f"{sid}.mdx").write_text(page)


def main() -> int:
    syllabus = json.loads((DATA / "syllabus.json").read_text())
    bank, warnings = load_bank()
    stats = write_bank(syllabus, bank)
    write_syllabus_meta(syllabus, stats)
    write_section_pages(syllabus, stats)
    total = sum(stats.values())
    print(f"bank compiled: {total} questions -> site/src/data/bank/ "
          f"({', '.join(f'{k}:{v}' for k, v in sorted(stats.items()))})")
    print(f"section pages: {len(syllabus['sections'])} -> site/docs/sections/")
    for w in warnings:
        print(f"  warn: {w}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
