import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The study guide sidebar is generated from the docs folder structure.
// Section pages (syllabus explorer) are generated by the build pipeline
// from data/syllabus.json.
const sidebars: SidebarsConfig = {
  studySidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
